# -*- coding: utf-8 -*-
"""clean_rawURLS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xypbD_qOuNugEWsz363Sl4RwXrfJlH_x
"""

import pandas as pd
import numpy as np

def question_lookup(url_list):
  return_list = []
  for url in url_list:
      if url.startswith("https://answers.justia.com/question/"):
          return_list.append(url)
  return return_list

df = pd.read_csv('2022-2023_NY.csv')
print(df.head(10))

all_urls = df['Unnamed: 1'].tolist()
all_urls = all_urls[1:]
print(all_urls)

question_urls = question_lookup(all_urls)
print(question_urls)
print('length: ' + str(len(question_urls)))